const CONFIG = {
    HOST: '',

    MEDIATOR: {
        EVENTS: {

        },
        TRIGGERS: {

        },
    },

    SOCKET: {
        LOGIN: 'LOGIN',
        LOGOUT: 'LOGOUT',
        GET_CONVERSATIONS: 'GET_CONVERSATIONS',
        GET_CONVERSATION_INFO: 'GET_CONVERSATION_INFO',
        GET_CONVERSATION_MESSAGES: 'GET_CONVERSATION_MESSAGES',
        SEND_MESSAGE: 'SEND_MESSAGE',
        NEW_MESSAGE: 'NEW_MESSAGE',
        GET_BLOCKED_USERS: 'GET_BLOCKED_USERS',
        BLOCK_USER: 'BLOCK_USER',
        GET_BOTS: 'GET_BOTS',
        ADD_BOT: 'ADD_BOT',
        UPDATE_BOT: 'UPDATE_BOT',
        DELETE_BOT: 'DELETE_BOT',
        DELETE_ALL_CONVERSATIONS: 'DELETE_ALL_CONVERSATIONS',
    },
}

export default CONFIG;